version: "3"
env:
  PGM_NAME: microgpt-zig
tasks:
  build:
    desc: Build the project
    cmds:
      - zig build

  build:release:
    desc: Build in release mode
    cmds:
      - zig build -Doptimize=ReleaseFast

  run:
    desc: Build and run
    cmds:
      - zig build run

  run:release:
    desc: Build and run in release mode
    cmds:
      - zig build run -Doptimize=ReleaseFast

  demo:
    desc: Train a tiny GPT on names dataset and generate new names (ReleaseFast)
    cmds:
      - echo "=== microgpt-zig demo ==="
      - echo "Training a 1-layer, 16-dim GPT on character-level names for 1000 steps..."
      - echo ""
      - zig build run -Doptimize=ReleaseFast

  demo:korean:
    desc: Train on Korean (Hangul) names and generate new ones
    cmds:
      - echo "=== microgpt-zig demo (Korean/한국어) ==="
      - echo "Training a 1-layer, 16-dim GPT on Hangul names for 1000 steps..."
      - echo ""
      - zig build run -Doptimize=ReleaseFast -- data/korean_names.txt

  test:
    desc: Run tests
    cmds:
      - zig build test

  bench:
    desc: Benchmark (3 runs, best wall time, ReleaseFast)
    cmds:
      - zig build -Doptimize=ReleaseFast
      - |
        best=""
        for i in 1 2 3; do
          out=$(/usr/bin/time -l ./zig-out/bin/microgpt-zig 2>&1)
          timeln=$(echo "$out" | grep 'real')
          wall=$(echo "$timeln" | awk '{print $1}')
          user=$(echo "$timeln" | awk '{print $3}')
          sys=$(echo "$timeln" | awk '{print $5}')
          rss=$(echo "$out" | grep 'maximum resident' | awk '{print $1}')
          rss_mb=$(echo "scale=1; $rss / 1048576" | bc)
          instr=$(echo "$out" | grep 'instructions retired' | awk '{print $1}')
          instr_b=$(echo "scale=1; $instr / 1000000000" | bc)
          loss=$(echo "$out" | grep 'step 1000' | sed 's/.*loss //')
          s1=$(echo "$out" | grep 'sample  1:' | sed 's/.*: //')
          echo "run $i: ${wall}s wall, ${user}s user, ${sys}s sys, ${rss_mb}MB RSS, ${instr_b}B instr | loss=$loss sample1=$s1"
          if [ -z "$best" ] || [ "$(echo "$wall < $best" | bc)" -eq 1 ]; then
            best=$wall
          fi
        done
        echo ""
        echo "best: ${best}s"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf zig-out .zig-cache

  loc:
    desc: Count lines of code
    cmds:
      - tokei
